### ISSUE TITLE
1.7.10 Version not working on server

### ISSUE THREAD

**Issue by DarkShadow44** [DarkShadow44/SereneSeasons#1]
Probably because I try to run client side code on the server. I'll look into it.

**Comment by DarkShadow44** [comment]
@Mnesikos Can you please try the attached update?

For me it works with a vanilla setup. If it doesn't work for you, can you please provide a full log?

EDIT: Removed link.

**Comment by Mnesikos** [comment]
Seems to be working on our end as well! If anything comes up, I'll be sure to open a new issue here. Thanks so much for getting to this quickly!

**Comment by kaliflowerx3** [comment]
hey im working with mnesikos on this, the server boots up now and colours work however trying to access the creative menu on servers (singleplayer works fine) crashes the server, heres the log

[ss-crashlog.log](https://github.com/DarkShadow44/SereneSeasons/files/4050290/ss-crashlog.log)

**Comment by DarkShadow44** [comment]
Well, some mod is broken and registering an item without a proper name, making forge crash when SereneSeasons calls into it.
FWIW I already encountered it, some time ago, but don't know why. Time for another workaround.

Can you please try? I can't reproduce the crash, but this should fix it. 

EDIT: Removed link.

**Comment by kaliflowerx3** [comment]
That fixed the creative menu crash, but there was a new crash with the seasons clock. When i changed it to early_spring the animation played on the clock but then crashed shortly after:

[crash-2020-01-12_14.14.02-client.txt](https://github.com/DarkShadow44/SereneSeasons/files/4051173/crash-2020-01-12_14.14.02-client.txt)

**Comment by kaliflowerx3** [comment]
btw thanks so much for helping us with this

**Comment by DarkShadow44** [comment]
Meh, I'll look into it. Simple out-of-bound, I guess. Only affects the client, right?

**Comment by kaliflowerx3** [comment]
yeah only the client

**Comment by DarkShadow44** [comment]
Should be fixed in the code. Anyways, since this is about the server, closing. Still need to work out how release will be handled, I'm dependent on the autors of SereneSeasons for that.
