### ISSUE TITLE
Nearly entire removal of snow on chunk generation [1.7.10]

### ISSUE THREAD

**Issue by AstroTibs** [DarkShadow44/SereneSeasons#10]
When new chunks load, all surface snow tiles are removed except one specific chunk position. This results in a regular dot pattern. You can see it on the ground and in the JourneyMap: https://i.imgur.com/zGw6JQB.png

This happens even when starting a new world at **mid_winter**, with no other mods, in an ice plains biome, and for all combinations of the two "weather settings" config options.

Snow blocks (cubes) are unaffected. This only affects the surface-level chunk decoration. In this JourneyMap overhead, the white blocks are snow blocks. The brown are grass blocks that would be covered by snow tiles if generated without SS: https://i.imgur.com/xVbGv2W.png

**Comment by DarkShadow44** [comment]
Thanks for reporting, that's interesting. The spotting should not happen.
I'm guessing the snow should not disappear at all during winter?

Could you provide a seed for easier testing, preferably using only vanilla and SereneSeasons?

**Comment by AstroTibs** [comment]
Hi, yeah, IMO the snow should _always_ appear as decoration on chunk generation—or at least all times but summer—and that it should disappear gradually based on weather and/or temperature.

I've been using seed **59** for those screencaps.

Also in case it's relevant, I used SereneSeasons-1.7.10-1.2.19.jar built on my end from the code here.

**Comment by ORANG4** [comment]
I agree with "snow is present by default in the corresponding biomes" concept.
Sorry for bad english

**Comment by DarkShadow44** [comment]
Welp, when going through all blocks in a chunk, it's useful to not always use the same x an z for all blocks... I pushed a fix, thanks for finding that one!
