### ISSUE TITLE
Config mod crop defaults use 1.12 items

### ISSUE THREAD

**Issue by AstroTibs** [DarkShadow44/SereneSeasons#11]
This is a minor fix on the user's end if they know about it, but tedious and confusing if they don't. The config defaults for all crops reference the 1.12 Harvestcraft/Growthcraft items, but those aren't the names used by 1.7.10 so essentially everything is at the whim of the `ignore_unlisted_crops` config entry.

For Harvestcraft, the user simply needs to change all crops ending with `item` to `Item`. However, it's wise not to use a simple find-and-replace, because that would incorrectly change wh**item**ushroomitem and wh**item**ushroomseeditem.

Here are the config values I set up for my own use, including EtFuturum and Gany's Surface values for beetroot, JAFFA's value for kale, and Witchery and Natura's crops, if you want to use some or all of them to replace the packaged values:

https://pastebin.com/aKUmmMNB

**Comment by DarkShadow44** [comment]
Looks sensible to me, thanks, I'll take it!
I pushed a fix, does fix the default config for you? You might have to regenerate it though.

**Comment by AstroTibs** [comment]
Everything seems to be in order. Obviously there are a couple 1.12 values in there that simply don't exist in 1.7, but I don't consider that to be problem because it doesn't rub up against functionality.
