### ISSUE TITLE
Crash on Startup with Gany's Surface

### ISSUE THREAD

**Issue by PopcornHead51** [DarkShadow44/SereneSeasons#14]
top says it
[crash-2020-03-05_00.13.30-client.txt](https://github.com/DarkShadow44/SereneSeasons/files/4291091/crash-2020-03-05_00.13.30-client.txt)

**Comment by DarkShadow44** [comment]
Seems to work for me. Did you compile the latest version from source?

**Comment by PopcornHead51** [comment]
How does one do that?

**Comment by DarkShadow44** [comment]
I updated the readme: https://github.com/DarkShadow44/SereneSeasons/blob/1.7.10_backport/README.md

**Comment by PopcornHead51** [comment]
whenever I try to type in the "gradlew reobf" command I get the error
FAILURE: Build failed with an exception.

* What went wrong:
Could not determine java version from '14'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

**Comment by DarkShadow44** [comment]
You probably need jdk8. Your java is simply... too new.

**Comment by DarkShadow44** [comment]
Any news on this?

**Comment by PopcornHead51** [comment]
yea it's fixed
