### ISSUE TITLE
Crashing but not sure which mod is the culprit

### ISSUE THREAD

**Issue by Cheremenin** [DarkShadow44/SereneSeasons#19]
[crash-2020-07-03_23.12.44-client.txt](https://github.com/DarkShadow44/SereneSeasons/files/4871328/crash-2020-07-03_23.12.44-client.txt)

Trying to put together a modpack for my local server, getting this, any ideas?

**Comment by DarkShadow44** [comment]
Make sure to compile the latest version from my git: https://github.com/DarkShadow44/SereneSeasons/tree/1.7.10_backport
Chances are, the issue is already fixed.
