### ISSUE TITLE
Non-Emergent Issues & Suggestion

### ISSUE THREAD

**Issue by Mnesikos** [DarkShadow44/SereneSeasons#2]
Hey again! Didn't want to clog up the other issue with anything that wasn't top priority, hope this is alright.

A couple of things we've noticed on the server so far has to do with the `/ss setseason` command.
- ArrayIndexOutOfBoundsException exception in the console when run without an arg after setseason [https://hastebin.com/jipudugusu.md](https://hastebin.com/jipudugusu.md) (and perhaps if too many args are set)
- Suggestion: outputting the options for the command (which season strings are acceptable) would be pretty helpful, and even a tab completion entry for it perhaps?

Another thing we've run into is a slight render issue with the greenhouse glass block: 
![image](https://user-images.githubusercontent.com/36017380/72215298-5d8b8f00-34df-11ea-8cbb-856313fd9097.png)

Thanks!

**Comment by DarianLStephens** [comment]
I'm having the opposite issue with the greenhouse block. It renders fine in the inventory, hotbar, and world, but in my hand it's solid blue:
![2020-01-14_15 56 46](https://user-images.githubusercontent.com/15375876/72315369-a497a100-36e6-11ea-8ae2-41fa4335c2a3.png)

Also, this isn't really related, but it looks like the glass doesn't let light through?
![2020-01-14_15 57 23](https://user-images.githubusercontent.com/15375876/72315406-c5f88d00-36e6-11ea-9e0e-17576b47281f.png)
No clue if it was that way in the 1.12 mod, but it seems weird for glass.

**Comment by DarianLStephens** [comment]
Actually, it looks like it does let it through:
![2020-01-14_16 58 38](https://user-images.githubusercontent.com/15375876/72318034-3b685b80-36ef-11ea-89d2-d463006fb813.png)
It's probably not Ambient Occlusion, either, since glass has it. Not sure why blocks on the other side are darkened, even if the light level doesn't drop.

**Comment by DarkShadow44** [comment]
Commands are updated, glass is fixed. Thanks for reporting!
Again, first need to work out how a release will go. I can't provide one.
