### ISSUE TITLE
Crash with galacticraft please help!

### ISSUE THREAD

**Issue by Frafx** [DarkShadow44/SereneSeasons#21]
Game crashed with GC, i tried a new forge installation with ONLY serene mod and GC in 1.7.10 the problem seems it come from middlecore.

Please fix this if possible, is litteraly the only mod for season in 1.7.10 

[crash-2020-12-05_00.36.27-client.txt](https://github.com/DarkShadow44/SereneSeasons/files/5646060/crash-2020-12-05_00.36.27-client.txt)

**Comment by DarkShadow44** [comment]
Can't reproduce, can you please test with SereneSeasons-1.7.10-1.2.19 ? You need to build from source for that, though...

**Comment by Frafx** [comment]
> SereneSeasons-1.7.10-1.2.19

Where i can found 1.2.19? The only downloades aviable that i found are on CruseForge wich have only 1 version for 1.7.10.
It's really frustrating, if you could add me on discord it would it be better and easy, then i'll post here the fix. Frafx#3771
Im also really glad you considereted my problem i tought no one will answer ^^
I writed that the problem is with micdodlecore but actually it works, if i add galacticraft it dont

**Comment by DarkShadow44** [comment]
As I said, it's not on CurseForge. You need to actually build the mod yourself, from source.

**Comment by Frafx** [comment]
Problem has been fixed in the last dev version. SereneSeasons-1.7.10-1.2.19
