### ISSUE TITLE
Cant build from the source code

### ISSUE THREAD

**Issue by SusLord1** [DarkShadow44/SereneSeasons#22]
Disclaimer that I have no coding experience whatsoever, at first it didn't work because I didn't have the JDK installed or set my JAVA_HOME. Now I just get this error: 
Could not determine java version from '15.0.2'.

The curseforge version works in singleplayer but crashes servers, which is what I've been trying to fix.

**Comment by KibaTheBarbarian** [comment]
the one on curseforge is out of date you got to compile your own version here

**Comment by SusLord1** [comment]
@KibaTheBarbarian i know, i was having problems with it crashing my server. But compiling it isn't working for me due to that error

**Comment by DarkShadow44** [comment]
You need OpenJDK8. You currently have JDK 15, which is too new.

**Comment by SusLord1** [comment]
works now, thanks
