### ISSUE TITLE
[CRASH] Serene Seasons not compatible with Mohist server

### ISSUE THREAD

**Issue by TekuSP** [DarkShadow44/SereneSeasons#23]
Serene Seasons (built from git, commit 5d681c218a101e1f748e89d2b30ad91284062816 ) for 1.7.10, completely blocks startup of Mohist server, version 28.
Attaching logs from server:
[fml-server-latest.log](https://github.com/DarkShadow44/SereneSeasons/files/6303348/fml-server-latest.log)
[latest.log](https://github.com/DarkShadow44/SereneSeasons/files/6303349/latest.log)
[fml-junk-earlystartup.log](https://github.com/DarkShadow44/SereneSeasons/files/6303350/fml-junk-earlystartup.log)

Running on Windows 10 (Build 19042.906 20H2)
java version "1.8.0_281"
Java(TM) SE Runtime Environment (build 1.8.0_281-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.281-b09, mixed mode)

Removing Serene Seasons solves the problem, but I would love to use it.

**Comment by TekuSP** [comment]
I gave up on Mohist.

**Comment by DarkShadow44** [comment]
Great, another verify error... Those are the worst.

I pushed a fix, can you please test?

**Comment by TekuSP** [comment]
It looks like it helped!

Thank you a lot.
