### ISSUE TITLE
Crash when entering the Nether

### ISSUE THREAD

**Issue by AstroTibs** [DarkShadow44/SereneSeasons#26]
I should point out that I get this error from time to time when simply signing into worlds, but now it happens 100% of the time when building a new Nether on a new world.

`Class transformer null safety: found misbehaving transformers: sereneseasons.asm.transformer.WeatherTransformer(sereneseasons.asm.transformer.WeatherTransformer@2c8d0dee) crashed with java.lang.NullPointerException(null),sereneseasons.asm.transformer.ColorTransformer(sereneseasons.asm.transformer.ColorTransformer@67aa8ce9) crashed with java.lang.NullPointerException(null)`

**Comment by DarkShadow44** [comment]
Can I have a full log?

**Comment by AstroTibs** [comment]
Wow, sorry I forgot about this.

I can't say for certain right now, but I _believe_ the misbehaving transformers message was incidental, and that some other thing was causing the crash. I also re-built using `gradlew reobf` rather than the `gradlew build` that I usually do, and noticed the mod had a slightly different file size, so maybe that helped.

I'll re-open this if I find more such crashes in the future.
