### ISSUE TITLE
Provide prebuilt jars. I use 2 Java versions (8 and 17 for a launcher), and building fails due to this.

### ISSUE THREAD

**Issue by MagmaSlime123** [DarkShadow44/SereneSeasons#29]
Title.

![image](https://user-images.githubusercontent.com/51277766/210276731-3d2d956e-fba1-4e12-9920-59da3db1f05b.png)

**Comment by DarkShadow44** [comment]
Since this is 1.7.10, you need to use java 8 for building.

**Comment by MagmaSlime123** [comment]
I use 2 Java versions, read the title. MultiMC is a thing.

**Comment by DarkShadow44** [comment]
And you're building with the wrong one. You need to build with java 8.

**Comment by MagmaSlime123** [comment]
How.

**Comment by DarkShadow44** [comment]
Probably by setting JAVA_HOME. Not sure, since I'm on Linux, and it's a lot easier here.

**Comment by SilearFlare** [comment]
@MagmaBro123 
The mod compiles fine, please don't bother the dev with tech support about things that aren't inherently a problem with the mod itself and just your setup. That's not his job.

By the way, you forgot to cover the environment name in the window. :sweat_smile:

**Comment by MagmaSlime123** [comment]
Whoops. I almost never compile mods manually, so I have no idea how to do so. Just provide prebuilt jars, or use something to do so for you.

**Comment by DarkShadow44** [comment]
Due to license restrictions I don't provide prebuilds, it's provided as-is. Sorry about that, nothing I can do.

**Comment by anoomolu** [comment]
> How.

[Here](https://legacymoddingmc.github.io/wiki/#troubleshooting-1.7.10-build-scripts/) is a guide that walks you through building from source. I used this method to compile this mod and it works fine ^^
