### ISSUE TITLE
Found an incompatibility with Thaumicinfusion

### ISSUE THREAD

**Issue by Khikki** [DarkShadow44/SereneSeasons#3]
The problem is only in the client, the server is all right, since I installed your fix 1.2.19. 

I'm sorry for the brevity, I'm not a direct native English speaker.

[error.txt](https://github.com/DarkShadow44/SereneSeasons/files/4056830/error.txt)
[Full crash-2020-01-14_03.25.11-client.txt](https://github.com/DarkShadow44/SereneSeasons/files/4056844/crash-2020-01-14_03.25.11-client.txt)

**Comment by Khikki** [comment]
When you open the inventory in the creative randomly painted.*

[crash-2020-01-14_03.38.42-client.txt](https://github.com/DarkShadow44/SereneSeasons/files/4056879/crash-2020-01-14_03.38.42-client.txt)

**Comment by DarkShadow44** [comment]
Yeah, my bad, I fixed it in the code.
