### ISSUE TITLE
Crash with Serene Seasons regarding Buildcraft

### ISSUE THREAD

**Issue by JCRail** [DarkShadow44/SereneSeasons#30]
I get a crash on my Minecraft Server regarding Buildcraft and Serene Seasons. What it appears from the crash report posted is that it isn't simply finding the Buildcraft Biomes class files. It confuses me more as this only happens on Multiplayer and not Singleplayer.

[crash-2023-02-22_05.21.24-server.txt](https://github.com/DarkShadow44/SereneSeasons/files/10809660/crash-2023-02-22_05.21.24-server.txt)

**Comment by DarkShadow44** [comment]
Same thing happens with just buildcraft and serene seasons? And only in multiplayer?
That is a weird error indeed.

**Comment by JCRail** [comment]
So I did actually contact the BC Devs and they did find out more information about it. Here is the like to the issue.

https://github.com/BuildCraft/BuildCraft/issues/4697

**Comment by asiekierka** [comment]
Using client-side-only imports in a Mixin which is applied on the server-side is universally a bad idea, as these classes simply don't exist in that environment. See `BiomeMixin` and its usage of `net.minecraft.client.Minecraft`. You're going to need to use `@SideOnly`, if it works with 1.7 Mixin (I'd err towards no if you're unsure, but I genuinely don't know), or - failing that - split it into two Mixin classes, one general-purpose and one client-side-only.

**Comment by DarkShadow44** [comment]
Well, the methods in BiomeMixin that use Minecraft are already annotated as client-only. Not sure why that wouldn't work. Just to clarify, you did build from source, right?

**Comment by asiekierka** [comment]
I checked the log - user is using `1.2.18`, the issue was fixed in `1.2.19`. Guess that explains it - I only examined the JAR as provided in the modpack.

**Comment by DarianLStephens** [comment]
What's with all these issues being closed? Were you finally allowed to release your updates properly?

**Comment by DarkShadow44** [comment]
Nah, just cleanup. No need to keep issues around that are either solved or non-reproducable.
