### ISSUE TITLE
Crash with  hodgepodge  + hunger overhaul + Pam's HarvestCraft

### ISSUE THREAD

**Issue by kotmatross28729** [DarkShadow44/SereneSeasons#31]
With hodgepodge,  hunger overhaul and Pam's HarvestCraft everything is fine, but when adding serene seasons the game crashes
( more likely this is a bug of the hunger overhaul itself, but there is no issues button ¯\\\_(ツ)_/¯, I don't know )
## Crash mods:

[HungerOverhaul](https://github.com/GTNewHorizons/HungerOverhaul)
[Hodgepodge](https://github.com/GTNewHorizons/Hodgepodge)
[Pam's+HarvestCraft](https://www.curseforge.com/minecraft/mc-mods/pams-harvestcraft)
## Mod list: 

+ -unimixins-all-1.7.10-0.1.7.1
 + 0gtnhlib-0.0.13 (1)  
 + AppleCore-3.2.10   
+ hodgepodge-2.2.12  
+ HungerOverhaul-1.7.10-1.0.4-GTNH  
+ Pam's+HarvestCraft+1.7.10Lb   
+ SereneSeasons-1.7.10-1.2.19

## Crash report:
https://pastebin.com/Cs0atBrm

**Comment by kotmatross28729** [comment]
moved to https://github.com/GTNewHorizons/Hodgepodge/issues/214

**Comment by DarkShadow44** [comment]
Fixed in 1.3.0
