### ISSUE TITLE
[Shaders] rain puddles support with serene seasons

### ISSUE THREAD

**Issue by kotmatross28729** [DarkShadow44/SereneSeasons#32]
Some shaders (eg bsl) have rain puddles. But with serene seasons, in the winter season it snows instead of rain, but there are still rain puddles

https://github.com/DarkShadow44/SereneSeasons/assets/110309314/8ea7bfa6-3b82-4ded-8010-7f6466de4502

**Comment by DarkShadow44** [comment]
Not sure I can even fix this. But can you provide the shaders (and shadermod) and everything else I need to reproduce?

**Comment by kotmatross28729** [comment]
+ [BSL_v8.2.03.13d.zip](https://github.com/DarkShadow44/SereneSeasons/files/11749291/BSL_v8.2.03.13d.zip) <---- shader
+ https://optifine.net/adloadx?f=OptiFine_1.7.10_HD_U_E7.jar <----- optifine
+ Serene seasons

1. put BSL_v8.2.03.13d.zip in shaders folder
2. create the world
3. set winter
4.  `/weather rain`
5. wait
6. this

**Comment by kotmatross28729** [comment]
Basically, to fix this, you need to somehow disable them during the winter season. They can be disabled in the shader files by opening the archive, further along the path `shaders\lib\reflections\rainPuddles.glsl` and find line 29 ` val + = texture2D(noisetex, ppos / 128.0 - frametime * 0.005).r * 0.35;` after it (that is, instead of the empty line 30) put `return val;`

It should turn out like this:
![1](https://github.com/DarkShadow44/SereneSeasons/assets/110309314/c59aebd2-fc3d-42b9-acf7-8c42d673dc90)

**Comment by DarkShadow44** [comment]
Seems to needs Shader Options -> Materials -> Advanced Materials : ON
And possibly another resource pack it says?
Anyways, I can't get ripples to work, please tell me what I need to do for ripples to appear.

**Comment by kotmatross28729** [comment]
Shader Options -> Materials  -> Specular & Reflections -> Rain Reflection : ON
(Should be enabled by default)

**Comment by kotmatross28729** [comment]
Try pressing "Reset" and enable Advanced Materials (And yet, what I showed above (in the shader files) is needed to disable ripples)

**Comment by DarkShadow44** [comment]
Alright, I thought it only happens on water... It works now, and I'm looking into it

**Comment by DarkShadow44** [comment]
Should be fixed by d448a17ea700d5054daa19b0cc9894e3d4f5f776.
It's a hacky hack, but it works. Please test...

**Comment by kotmatross28729** [comment]
> Should be fixed by d448a17

Wow, I didn't even think you'd be working on this. But you did! Thank you very much!
(I tested it and it works without problems, thanks again!)
