### ISSUE TITLE
Can't build gradle

### ISSUE THREAD

**Issue by BastardNeko** [DarkShadow44/SereneSeasons#33]
It just returns "Could not determine java version from 17." No matter what I try, I can't get it to work.  I checked and I have java 8. Please help. I'm stuck on the version from Curseforge that has the bug where the greenhouse glass is opaque when using optifine and I kinda need optifine.

**Comment by DarkShadow44** [comment]
You do have the JDK for java 8, right?
Well, you might have java 8, but you also need to make sure it's the default. On Windows, you probably need to set PATH and JAVA_HOME accordingly. Can't say for sure, since I work on Linux.

**Comment by BastardNeko** [comment]
Got it to work, thank you!

**Comment by DarkShadow44** [comment]
No problem, please add the solution for others who find this through google. :)

**Comment by BastardNeko** [comment]
This was the walkthrough I followed. https://mkyong.com/java/how-to-set-java_home-on-windows-10/
