### ISSUE TITLE
Bonemealing Bug w/ "Crops Break" Setting

### ISSUE THREAD

**Issue by caseytimesthree** [DarkShadow44/SereneSeasons#37]
Setting "crops break" out of season to true will make it so anything bonemealed will be destroyed out of season. This is probably intentional behaviour for plants, but it also includes the following blocks: dirt, grass & bedrock.

**Comment by SilearFlare** [comment]
Yes, there is an issue with bonemeal basically becoming an infinite block breaker as long as you hold on right click that can get rid of absolutely anything. It's pretty funny.

**Comment by KibaTheBarbarian** [comment]
@DarkShadow44 can this get fix

**Comment by DarkShadow44** [comment]
I'll take a look when I find time for it.

**Comment by DarkShadow44** [comment]
Should be fixed now.
