### ISSUE TITLE
Possible DragonAPI compatability at all?

### ISSUE THREAD

**Issue by Cynosphere** [DarkShadow44/SereneSeasons#4]
I doubt this will be possible as mixins are archaic to the 1.7.10 ecosystem, especially when you have regular ASM patches thrown in.

Because of the method being renamed to `colorMultiplierOld`, DragonAPI throws a fit.

```
Method func_149720_d (Lnet/minecraft/world/IBlockAccess;III)I not found in class net/minecraft/block/BlockLiquid.
This is a critical ASM error and the class transformer operation cannot proceed. If you are the developer of this mod, check for proper use of SRG/deobf names and/or sideonly elements. If not, report it to the developer.
```

Maybe theres some way to delay the mixin until after DragonAPI's ASM is done? I've only ever messed with mixins in Fabric so.

**Comment by DarkShadow44** [comment]
AFAIK, Mixin need to run before regular ASM transformers, because of the way it is registered. That with colorMultiplierOld is not a Mixin though, it's a regular ASM transformer. Maybe I can just delay that.

**Comment by DarkShadow44** [comment]
What a mess. Actually, Mixin forces our ASM transformer to run early, because it injects it manually, bypassing forge logic. Kind of problematic, since neither that old forge nor that old mixin is supported.
I pushed a fix, can you please test?

**Comment by Cynosphere** [comment]
No crash at all, even tested loading into a world and it all seems to work fine.
