### ISSUE TITLE
[1.7.10] Crash with galacticraft

### ISSUE THREAD

**Issue by Kkelos** [DarkShadow44/SereneSeasons#41]
https://pastebin.com/uusiYWB2

It seems a conflict with galacticraft's falling meteors color & serene seasons color change based on season, i think

**Comment by DarkShadow44** [comment]
Did you compile the latest version from source?

**Comment by Kkelos** [comment]
> Did you compile the latest version from source?

No, i just downloaded the mod from curseforge. What should i do ? (Sorry, im new to it)

**Comment by Kkelos** [comment]
Should i download zip and run gradlew.bat ?
![Screenshot_20240807_224804_Chrome.jpg](https://github.com/user-attachments/assets/9f59120b-0965-4c98-9e34-e8c3f506d132)

**Comment by DarkShadow44** [comment]
Yes, pretty much. You need to run "gradlew reobf", the output will be in "build/libs/"

**Comment by Kkelos** [comment]
Ok, I'll try it and tell you in ~15 hours  (cuz i don't have access to a computer rn)

**Comment by Kkelos** [comment]
> Yes, pretty much. You need to run "gradlew reobf", the output will be in "build/libs/"

Right now, i ran command "gradlew reobf" in windows cmd in "SereneSeasons-master" folder. It seems not working, what should i do ? (i ran it with JDK21 & JDK22.0.2) 

![image](https://github.com/user-attachments/assets/347d05c7-6b4c-4b7d-a585-c681adbe30cf)

**Comment by Kkelos** [comment]
> > Yes, pretty much. You need to run "gradlew reobf", the output will be in "build/libs/"
> 
> Right now, i ran command "gradlew reobf" in windows cmd in "SereneSeasons-master" folder. It seems not working, what should i do ? (i ran it with JDK21) 
> 
> ![image](https://github.com/user-attachments/assets/347d05c7-6b4c-4b7d-a585-c681adbe30cf)
> 

No no no, it seems to work with jdk-21.0.4

**Comment by Kkelos** [comment]
> Yes, pretty much. You need to run "gradlew reobf", the output will be in "build/libs/"

Anyway, i tried all jdk versions (22, 21, 17. Downloaded by .zip or installer). Didnt work, same issue. What should I do ?

**Comment by SilearFlare** [comment]
> > Yes, pretty much. You need to run "gradlew reobf", the output will be in "build/libs/"
> 
> Anyway, i tried all jdk versions (22, 21, 17. Downloaded by .zip or installer). Didnt work, same issue. What should I do ?

You're really not supposed to use new versions to compile mods for a 10+ year old version of minecraft, that's the main issue. Compiling mods for 1.7 is another thing entirely. 
I guess it's a bit of an esoteric topic but still, java 17+ doesn't work with minecraft 1.7 in the first place, and just checking the old issues of this repo alone should have given you that information. What you need is JDK 8. See #22

**Comment by Darek505** [comment]
You also downloaded the wrong source, the one in main is for 1.12.2. backport 1.7.10 is in another branch. 

<details>

<summary>Brief instructions on where to find it.</summary>


![1](https://github.com/user-attachments/assets/1dabd17c-2d5c-474b-8785-4f2d6a33db24)
![2](https://github.com/user-attachments/assets/1cda13db-5952-4326-9f4e-8511ca135ae7)
![3](https://github.com/user-attachments/assets/d8e8139e-ec4d-41f2-8d01-1ebff5d5f04e)


</details>

**Comment by Kkelos** [comment]
Ok, thanks for helping me ! I'll test it

**Comment by Kkelos** [comment]
> You're really not supposed to use new versions to compile mods for a 10+ year old version of minecraft, that's the main issue. Compiling mods for 1.7 is another thing entirely. I guess it's a bit of an esoteric topic but still, java 17+ doesn't work with minecraft 1.7 in the first place, and just checking the old issues of this repo alone should have given you that information. What you need is JDK 8. See #22

Well, im trying to run "gradlew reobf" with JDK-8 (Downloaded from oracle java archive "jdk-8u411-windows-x64.exe"). It just doesnt work, but it see JDK-21 
![cmdgradlewpic](https://github.com/user-attachments/assets/5a0cd819-ae77-4542-9e36-f5ca905e2794)

**Comment by Kkelos** [comment]
> You're really not supposed to use new versions to compile mods for a 10+ year old version of minecraft, that's the main issue. Compiling mods for 1.7 is another thing entirely. I guess it's a bit of an esoteric topic but still, java 17+ doesn't work with minecraft 1.7 in the first place, and just checking the old issues of this repo alone should have given you that information. What you need is JDK 8. See #22

 So, im tried to run "gradlew reobf" with jdk8 and it is not working (but working with jdk21 (error) ). I tried with jdk8 from oracle java archive (jdk-8u411-windows-x64.exe) and from adoptium.net (jdk8u422-b05 as .zip). It is not working with jdk8, but it see jdk21 
![image](https://github.com/user-attachments/assets/9047dc33-e69d-42dd-b065-38cb4a3937ff)

**Comment by DarkShadow44** [comment]
You didn't setup JDK8 correctly. Not sure how to on windows, since I'm on Linux.

**Comment by Darek505** [comment]
@Kkelos 

<details>

<summary>here are instructions on how to setup it to windows </summary>

### *Environment Variables*

![1](https://github.com/user-attachments/assets/1410c3f1-a84f-4217-a18f-79cece43c0fc)

---

![2](https://github.com/user-attachments/assets/b18d0a24-1a01-4c5c-9dd4-464d276c8bac)
![3](https://github.com/user-attachments/assets/9db72047-b574-4970-ac19-90055d69a279)
![4](https://github.com/user-attachments/assets/56b51451-ed9d-4d2a-99db-b437b45b8dc3)

---
### *path where jdk8\bin*


![5](https://github.com/user-attachments/assets/d2911870-11c8-40e9-afe2-c5b004083c54)
![6](https://github.com/user-attachments/assets/318f43b5-b782-400b-b2f2-1fc07f2fb5cc)


you also need to install gradle 4.4.1 - https://gradle.org/releases/

in order, gradle 4.4.1 should be the top one in the list, below it comes jdk 8

</details>

**Comment by Kkelos** [comment]
> here are instructions on how to setup it to windows

Ok, i'll try it

**Comment by Kkelos** [comment]
@Darek505 
Thank you so much. It works !

@DarkShadow44 
I just built mod from source and playing minecraft, and there are no crashes.

Thank yall so much for helping me !

**Comment by DarkShadow44** [comment]
Glad it works now! Sorry for not being able to provide an up-to-date binary, but that was one of the things the original authors didn't want. Don't go bother them about it though! I feel like my fork already cost them enough nerves to begin with...
