### ISSUE TITLE
[1.7.10] Crash with GeoStrata

### ISSUE THREAD

**Issue by githubgarry73** [DarkShadow44/SereneSeasons#42]
Instant crash when entering a world. Only mods installed are DragonAPI, GeoStrata and Serene Seasons (freshly built from source).

Crash log:
[crash-2024-10-16_08.44.03-client.txt](https://github.com/user-attachments/files/17390573/crash-2024-10-16_08.44.03-client.txt)

**Comment by DarkShadow44** [comment]
Thanks for the report, I pushed a fix. Please retest, and close if fixed.

**Comment by githubgarry73** [comment]
just tested it, works like a charm, thanks!
