### ISSUE TITLE
Crash on server start

### ISSUE THREAD

**Issue by RailroadRider** [DarkShadow44/SereneSeasons#6]
I copied this from my singleplayer pack, it's identical aside from the Millenaire server/client files. Serene Seasons crashes with a Null Pointer exception.
[crash-2020-02-03_20.07.38-server.txt](https://github.com/DarkShadow44/SereneSeasons/files/4147025/crash-2020-02-03_20.07.38-server.txt)

**Comment by DarkShadow44** [comment]
Sounds like a dupe. Did you compile from source for the latest version?

**Comment by syndicate25** [comment]
I tried to compile this from the latest version available on your fork, and I get the following when starting on a server:

https://pastebin.com/u4iytxQ8

**Comment by DarkShadow44** [comment]
Can you post a full log?

**Comment by syndicate25** [comment]
There is no crash report, so there's the fml-latest.log.

https://pastebin.com/GuXCQXBL


EDIT: Upon further inspection of my own log, looks like an incompatibility for BNBGamingLib-2.3.2  and/or SuspendedServer-1.0.1.  I'll open a new issue.

**Comment by DarkShadow44** [comment]
Is this still an issue or is the other issue what remains?

**Comment by Tomcatchriss** [comment]
Same here.

## Issue Report

</br>

### What's the issue you encountered?

Using Forge 10.13.4.1614 for MC 1.7.10 and Serene Seasons for 1.7.10 - Version 1.2.18 crashing on startup.</br>

### How can the issue be reproduced?

I'm only using forge-1.7.10-10.13.4.1614-1.7.10-universal.jar and SereneSeasons-1.7.10-1.2.18.jar as the only one mod.</br>

I'm using a linux server running Ubuntu and Java OpenJDK 1.8.0_242.</br>

### Logs
[Crash Log](https://pastebin.com/jHKSCgWq)
</br>

### Mod Version
SereneSeasons-1.7.10-1.2.18.jar and also compiled SereneSeasons-1.7.10-1.2.19.jar</br>

**Comment by DarkShadow44** [comment]
Following up, this the main thing reported still a problem?
