### ISSUE TITLE
BNBGamingLib and/or SuspendedServer mod incompatibility

### ISSUE THREAD

**Issue by syndicate25** [DarkShadow44/SereneSeasons#8]
Crash on initial load, no crash report.  Here is the fml-latest.log instead:

https://pastebin.com/GuXCQXBL

Removing these 2 mods allows the server to start without an issue.

**Comment by DarkShadow44** [comment]
Sorry, I can't reproduce. Is just SereneSeasons with BNBGamingLib and SuspendedServer enough to trigger the issue? Or do I need more?

**Comment by DarkShadow44** [comment]
Any news on this?
